;; This file is automatically generated by the grammalecte extension.
;; It keeps track of the last attempt to check upstream version of Grammalecte.
(:check-timestamp 1662571744.877282 :version 2.1.1)
