

*** Programming 
Lsp + autres choses. LSP gère tout, le reste se connecte à lsp. De plus, je hook les modes à lsp, et j'active le reste lorque lsp-mode est activé. Mettre les commandes pour installer les languages server protoc

Pour installer facilement un language server protocol, deux cas :
1. Soit vous avez lsp ou lsp-nomDuLanguage (comme lsp-java) qui existe, vous l'activer correctement avec le mode (java, C, etc), et LSP va alors voir qu'il n'y a aucun language server protocol d'installer.
   dans ce cas, il va le télécharger (une fois), puis se connecter et en avant.
2. Sinon, il va falloir télécharger manuellement le language-server-protocol pour que LSP le détecte et se connecte à celui-ci. Suivre les instructions ici :
   https://emacs-lsp.github.io/lsp-mode/page/languages/

[[https://www.mortens.dev/blog/emacs-and-the-language-server-protocol/index.html][un lien qui permet peut-être de mieux expliquer ?]]
   
**** Lsp 
***** Lsp moteur + quand se déclare lsp
****** Moteur de lsp-mode
#+begin_src emacs-lisp

  (use-package lsp-mode
    :hook (((
             ;; les modes qui active lsp, et donc tout le reste
             typescript-mode
             js2-mode
             web-mode
             c-mode
             python-mode
             java-mode
             )
            . lsp)

           ;; compatibilité avec which-key
           (lsp-mode . lsp-enable-which-key-integration)
           )
    :config
    ;; pour mapper lsp-command-map
    (define-key lsp-mode-map (kbd "C-c l") lsp-command-map)

    ;;pour de meilleurs performances
    ;; (setq gc-cons-threshold 100000000)
    ;; (setq read-process-output-max (* 1024 1024)) ;; 1mb
    ;; (setq lsp-idle-delay 0.500)
    (setq lsp-log-io nil) ; if set to true can cause a performance hit

    ;; les options, voir le lien au dessus

    ;; (setq lsp-ui-doc-enable nil)
    ;; (setq lsp-ui-doc-show-with-cursor nil) ;; enlever les gros pavés qui se mettent à chaque fois
    )


#+end_src
****** Lsp-ui (pour les infos qd curseur dessus)
#+begin_src emacs-lisp
  (use-package lsp-ui
    :hook (lsp-mode . lsp-ui-mode)
    :custom
    (lsp-ui-doc-position 'bottom))
#+end_src
****** Pour les fichiers sur le côté
#+begin_src emacs-lisp
  (use-package lsp-treemacs
    :after lsp
    :config
    ;; pour syncro les dossier treemacs avec lsp
    ;;suis pour lsp
    ;; (lsp-treemacs-sync-mode 1)	 
    )
#+end_src

***** New language understand with emacs + lsp mode
****** C
****** TODO Python

#+begin_src emacs-lisp

  ;; (use-package lsp-jedi
    ;; :config
    ;; (with-eval-after-load "lsp-mode"
      ;; (add-to-list 'lsp-disabled-clients 'pyls)
      ;; (add-to-list 'lsp-enabled-clients 'jedi)))

  (setq python-shell-interpreter "/usr/bin/python3")

  ;; pour éviter les erreurs de doctstring	
  (setq lsp-pylsp-plugins-pydocstyle-enabled nil)

#+end_src

#+begin_src emacs-lisp :tangle no

  (use-package python-mode
    :config
    ;; (setq python-shell-interpreter "python3")
    ;; (setq python-shell-interpreter "ipython")
    ;; (setq python-shell-interpreter-args "~/anaconda3/lib/python3.8/site-packages/bokeh/_testing/plugins/ipython.py") 
    (require 'dap-python)

    (add-to-list 'auto-mode-alist '("\\.rpy\\'" . python-mode))
    )


#+end_src
****** Java                                                        :Low:

#+begin_src emacs-lisp

    ;; (use-package aggressive-indent-mode)
  ;; (add-hook 'java-mode-hook #'aggressive-indent-mode)



    ;; pour corriger la variable $JAVA_HOME avec asdf. a supprimer ?
    (use-package exec-path-from-shell
      :after lsp-mode org-roam
      :config
      (exec-path-from-shell-initialize)
      )
    ;; (when (daemonp)
    ;; (exec-path-from-shell-initialize)
    ;; )

    (use-package lsp-java
      :config
      ;; (setq lsp-java-jdt-download-url  "https://download.eclipse.org/jdtls/milestones/0.57.0/jdt-language-server-0.57.0-202006172108.tar.gz")
      )
#+end_src

****** JavaScript

#+begin_src emacs-lisp
  ;; (use-package lsp-javascript-typescript)
#+end_src

****** Dart

Il faut aussi installer flutter sur asdf

#+begin_src emacs-lisp :tangle no
(use-package dart-mode)
(use-package lsp-dart)
(add-hook 'dart-mode-hook 'lsp)
#+end_src



**** Completion et proposition
***** Voir les propositions avec company

Auto-complete existe aussi, mais pas aussi efficace.
****** Le moteur

Company-backend = variable qui possède la complétion. Seul le premier backend est utilisé (si il est valide dans le mode je suppose). On peut combiner les backend avec un ":with"

#+begin_src emacs-lisp

  (use-package company
    :after lsp-mode  ;;si ya lsp-mode
    :hook (lsp-mode . company-mode)  ;; au lieu de lsp, mettre c-mode, python mode etc
    ;; (org-mode . company-mode)
    :custom
    (company-minimum-prefix-length 1) ;;taille avant que le popup arrive
    (company-idle-delay 0.6);;temps avant qu'il pop
    ;;pour cycler dans les sélections
    (company-selection-wrap-around t)



    ;; réglemeent des touches, assez explicite, sur azerty :
    ;; k i s 
    (define-key company-active-map (kbd "M-n") nil)
    (define-key company-active-map (kbd "M-p") nil)
    ;; (define-key company-active-map (kbd "s") #'company-select-next)
    ;; (define-key company-active-map (kbd "d") #'company-select-previous)
    (define-key company-active-map (kbd "C-s") #'company-select-next)
    (define-key company-active-map (kbd "C-d") #'company-select-previous)
    (define-key company-active-map (kbd "u") 'company-complete-selection)
    ;; (define-key company-active-map (kbd "SPC") #'company-abort)

    )

#+end_src


  ;; Mettre yasnippets dans company

  ;; ne pas y mettre dans :config
    (with-eval-after-load 'company
      ;;pour =activer les yasnippets dans company !!!!!!=
      (setq lsp-completion-provider :none)
      ;; Add yasnippet support for all company backends
      ;; https://github.com/syl20bnr/spacemacs/pull/179
      (defvar company-mode/enable-yas t
        "Enable yasnippet for all backends.")

      (defun company-mode/backend-with-yas (backend)
        (if (or (not company-mode/enable-yas) (and (listp backend) (member 'company-yasnippet backend)))
            backend
          (append (if (consp backend) backend (list backend))
                  '(:with company-yasnippet))))

      (setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))       
      )


test : 


(add-to-list 'company-backends '(company-capf :with company-dabbrev))
(setq company-backends '(company-dabbrev))
(setq company-backends '(company-capf))
(setq company-backends '(company-yasnippet))
(setq company-backends (mapcar #'company-mode/backend-with-yas company-backends))

ancien : 

#+begin_src emacs-lisp :tangle no
  (use-package company
    :config
    ;; (add-hook 'org-mode 'company-mode)
    (add-hook 'after-init-hook 'global-company-mode)
    )

  ;; Smartparens
  ;; To automatically close "]]" brackets and other parentheses,
  ;; you need a package called "smartparens" Set it up globally.
  (smartparens-global-mode t)

  ;; Company
  ;; You need package called `company`.
  ;; I believe what these variables are meant to do is self-explanatory.
  ;; You type minimum 2 characters and wait for ¼ seconds for the candidates
  ;; to appear automatically. It uses a backend `company-capf` (part of
  ;; `company`; capf stands for "completion-at-point function"). I would
  ;; call it inline automatic completion. Org-roam has functions to work
  ;; with `company-capf`.
  (add-hook 'after-init-hook 'global-company-mode)
  (setq company-minimum-prefix-length 2)
  (setq company-idle-delay 0.25)
  (add-to-list 'company-backends 'company-capf)

  ;; This enables candidates matching to be case-insensitive
  (setq completion-ignore-case t)

  ;; You need this for your org-roam part of configuration
  ;; This prevents it from automatically replacing [[Title of a note]]
  ;; into [[file:path/to/note][Title of a note]].
  ;;(setq org-roam-auto-replace-fuzzy-links nil)

  ;; Some keybindings for within Company mode
  ;; Use (with-eval-after-load) to defer the use of `company-active-map`.
  ;; Otherwise, Emacs will error when loading `init.el` as it does not
  ;; recognise any Company related variables and functions yet.
  ;; This delay is defined above as we load 'global-company-mode' with
  ;; `after-init-hook`.
  (with-eval-after-load 'company
    (define-key company-active-map (kbd "C-n") #'company-select-next)
    (define-key company-active-map (kbd "C-p") #'company-select-previous))

  (tool-bar-mode)

#+end_src

****** Pour l'esthétique de l'affichage

#+begin_src emacs-lisp
    (use-package company-box
      :after company ;;logique
      :hook (company-mode . company-box-mode) ;;logique également
      )
#+end_src

***** Candidats intelligent, se base sur la fréquence d'apparition

#+begin_src emacs-lisp

  (use-package company-prescient
    :after company
    :config
    (company-prescient-mode 1)
    ;; Remember candidate frequencies across sessions
    (prescient-persist-mode 1)
    )

#+end_src
***** Expand des choses préfaites

#+begin_src emacs-lisp

  (use-package yasnippet
    ;; si on veux les yas que en prog mode, décocher ça et cocher yas global mode
    ;; :hook (prog-mode . yas-minor-mode)
    :config
    (yas-reload-all)
    (yas-global-mode 1)
    (setq yas-triggers-in-field t) ;;appeler des snippets dans des snippets

    (define-key yas-minor-mode-map (kbd "<tab>") nil)
    (define-key yas-minor-mode-map (kbd "TAB") nil)
    (define-key yas-minor-mode-map (kbd "<C-tab>") 'yas-expand)
    )

  (use-package yasnippet-snippets ;; un pack de snippets
    :diminish)

#+end_src


**** Gestion de projet
#+begin_src emacs-lisp 
  (use-package projectile
    :config
    ;; (projectile-global-mode)
    ;;(setq projectile-completion-system 'ivy)
    )
#+end_src
**** Language without lsp
***** Elisp
****** xah fly elisp mode, pas encore utilisé
:LOGBOOK:
- State "DONE"       from "TODO"       [2022-10-02 Sun 22:37]
:END:

Documentation : 
http://ergoemacs.org/emacs/xah-elisp-mode.html

Liste des abbrev : M-x list-abbrevs

#+begin_src emacs-lisp 
  (use-package xah-elisp-mode
    ;; :disabled t

    :config
    ;; activer xah-elisp-mode à la place de emacs-lisp-mode. fait par défaut

    ;; copie hook of emacs-lisp-mode
    (dolist (hook emacs-lisp-mode-hook)
      (unless (string-equal hook "xah-elisp-mode")(add-hook 'xah-elisp-mode-hook hook)))

    ;; àjouter le correcteur de flycheck à xah-elisp-mode
    (flycheck-add-mode 'emacs-lisp 'xah-elisp-mode)
    (setq ido-enable-flex-matching t) ;; activer la recherche de mots avec le fuzzy search


)

#+end_src

****** Pour afficher joliment un

****** Pour ne pas voir des vieux saut de page mais de jolie lignes

#+begin_src emacs-lisp

(use-package page-break-lines
  :hook ((emacs-lisp-mode . page-break-lines-mode)))

#+end_src

***** TODO  Processing 3 (cours)

#+begin_src emacs-lisp :tangle no
  
  (use-package processing-mode)
  (add-to-list 'auto-mode-alist '("\\.pde\\'" . processing-mode))

  
  (setq processing-location "~/Téléchargements/processing-3.5.4/processing-java")
  
#+end_src
